import type { Metadata } from "next"
import { AppPrivacyPolicy } from "@/components/app-privacy-policy"

export const metadata: Metadata = {
  title: "Privacy Policy — Glowria: Skincare Routine",
  description: "Privacy Policy for Glowria: Skincare Routine.",
}

export default function GlowriaPrivacyPage() {
  return (
    <AppPrivacyPolicy
      appName="Glowria: Skincare Routine"
      eyebrow="GLOWRIA: SKINCARE ROUTINE"
      effectiveDate="January 28, 2026"
      hasSubscriptions
      permission={{
        title: "Camera & Photo Access",
        body: "The Application requires access to your device camera and photo library so you can capture or select facial images (selfies) for skin analysis and personalized skincare routine recommendations. The images are sent securely to our backend and analyzed by a third-party AI model (Google Gemini) to assess skin conditions and tailor guidance. Your selfies are used solely to deliver the skin analysis, are processed transiently and deleted shortly after processing, and are never used to train any AI models or shared for any other purpose.",
      }}
      thirdPartyServices={[
        "Google Gemini — AI skin analysis and content generation, accessed through our own backend",
        "Cloudflare Workers — backend and API hosting",
        "RevenueCat — subscription and in-app purchase management (on top of Apple In-App Purchase)",
        "Google Analytics for Firebase — anonymized usage analytics",
      ]}
      extraSections={[
        {
          title: "Information We Collect",
          body: (
            <>
              <p>
                To deliver the skincare experience, the Application may collect and store:
              </p>
              <ul className="ml-5 list-disc space-y-1.5 marker:text-[var(--color-magenta)]">
                <li>
                  Facial images (selfies) you capture or select — used only for skin
                  analysis and deleted shortly after processing
                </li>
                <li>
                  Skin analysis results — your Skin Health Score and dimension scores
                  (Acne, Pores, Oiliness, Dark Spots, Hydration)
                </li>
                <li>
                  Routine and progress data — your morning/evening steps, check-ins,
                  streaks, and weekly reports
                </li>
                <li>
                  Skin diary entries and lifestyle tags you choose to log (e.g. Sleep,
                  Water, Stress, Period, Diet) and how your skin feels
                </li>
                <li>
                  Subscription status and anonymized purchase events (via Apple and
                  RevenueCat)
                </li>
                <li>
                  Basic device and usage information (e.g. IP address, operating system,
                  in-app activity)
                </li>
              </ul>
            </>
          ),
        },
        {
          title: "AI Skin Analysis & Your Photos",
          body: (
            <>
              <p>
                Skin analysis and routine recommendations are generated using a
                third-party AI model, Google Gemini, which the Application accesses
                through our own backend hosted on Cloudflare Workers. When you take a
                skin scan, your selfie is transmitted securely to our backend, sent to
                Google Gemini for analysis, and the resulting scores and guidance are
                returned to you.
              </p>
              <p>
                Your selfies are used solely to provide this analysis. They are processed
                transiently, deleted shortly after processing, and are never used to
                train any AI models or sold or shared with third parties for advertising.
              </p>
            </>
          ),
        },
        {
          title: "Informational Use Only — Not Medical Advice",
          body: (
            <p>
              The Application provides general skincare and cosmetic guidance for
              informational purposes only. It does not provide medical diagnosis or
              treatment, is not a medical device, and does not operate in a regulated
              medical capacity. All analysis content is generated by our own system using
              Google Gemini. For any medical or dermatological concern, please consult a
              qualified healthcare professional.
            </p>
          ),
        },
      ]}
    />
  )
}
